Revert "build(deps): bump ffi from 1.12.0 to 1.13.1"
This reverts commit 6ec898a732489cc41f9c956b9fce153b20da774e and
brings us back to commit 9bc604eb95d5eb7e6d929a2cfdc8a108aac8b55c,
where we explicitly opted in to version 1.12.0 of ffi.

The reason being, there is a known issue with OSX that leads to
the following build error:

```
dyld: lazy symbol binding failed: Symbol not found: _ffi_prep_closure_loc
  Referenced from: /Users/christopherashton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/ffi-1.13.1/lib/ffi_c.bundle
  Expected in: /usr/lib/libffi.dylib

dyld: Symbol not found: _ffi_prep_closure_loc
  Referenced from: /Users/christopherashton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/ffi-1.13.1/lib/ffi_c.bundle
  Expected in: /usr/lib/libffi.dylib

[1]    66481 abort      GITHUB_TOKEN=$(cat ~/github_token.txt) NO_CONTRACTS=true bundle exec middlema
```

Downgrading to lower version fixes it.
It looks as though this should have been fixed in
ffi/ffi#787, but we're seeing the same
error as originally reported.

In the next commit I will add a Dependabot config which will
prevent a bump PR from being raised again.