Only unlink h1 if it exists
Some of our READMEs must be missing a h1, as the build was failing
with errors like:

Error processing resource for index: apps/licensify.html
undefined method `unlink' for nil:NilClass
 /Users/christopherashton/govuk/govuk-developer-docs/app/external_doc.rb:118:in `call'
 /Users/christopherashton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/html-pipeline-2.5.0/lib/html/pipeline/filter.rb:130:in `call'
 /Users/christopherashton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/html-pipeline-2.5.0/lib/html/pipeline.rb:124:in `block in perform_filter'
 /Users/christopherashton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/html-pipeline-2.5.0/lib/html/pipeline.rb:162:in `instrument'
 /Users/christopherashton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/html-pipeline-2.5.0/lib/html/pipeline.rb:123:in `perform_filter'
 /Users/christopherashton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/html-pipeline-2.5.0/lib/html/pipeline.rb:109:in `block (2 levels) in call'
 /Users/christopherashton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/html-pipeline-2.5.0/lib/html/pipeline.rb:108:in `each'
 /Users/christopherashton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/html-pipeline-2.5.0/lib/html/pipeline.rb:108:in `inject'
 /Users/christopherashton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/html-pipeline-2.5.0/lib/html/pipeline.rb:108:in `block in call'
 /Users/christopherashton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/html-pipeline-2.5.0/lib/html/pipeline.rb:162:in `instrument'
 /Users/christopherashton/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/html-pipeline-2.5.0/lib/html/pipeline.rb:106:in `call'
 /Users/christopherashton/govuk/govuk-developer-docs/app/external_doc.rb:52:in `parse'