Revert "Bump activesupport from 5.0.7.1 to 5.1.6.1"
Looks like this might be related to this issue in the
govuk-developer-docs Jenkins job:

  NoMethodError: undefined method `activate' for GovukTechDocs:Module

This reverts commit 48e5eb6f0e0ec82f18874a768310fd198d84b2fc.