Revert "Bump activesupport from 5.0.7.1 to 5.1.7"
This reverts commit ada44cebf1dac969073c52f8699e4a460eedd07b.

This bump is causing problems with invoking middleman which is
preventing the docs from building. Reverting before more investigation.

YAML Exception parsing govuk-developer-docs/data/rendering-apps.yml: Tried to load unspecified class: Symbol
bundler: failed to load command: middleman (govuk-developer-docs/.bundle/bin/middleman)
NoMethodError: undefined method `activate' for GovukTechDocs:Module
  govuk-developer-docs/.bundle/gems/govuk_tech_docs-1.8.2/lib/govuk_tech_docs.rb:51:in `block in configure'